import React, { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Camera, User, Users, Download, RefreshCw, Check, X, Sparkles, 
  Send, Maximize, Image as ImageIcon, Zap, AlertCircle, Plus, Heart, 
  Trash2, Copy, Film, CheckSquare, Eye, ExternalLink, HelpCircle
} from 'lucide-react';
import { useTheme } from '../src/contexts/ThemeContext';
import { generateScene, generateSceneVideoPrompt } from '../services/geminiService';

// Types definition
interface GeneratedScene {
  id: string;
  sceneNumber: number;
  inputImage: string; // The reference image used for this step
  generatedImage: string; // The generated result
  prompt: string; // Short prompt used
  videoPrompt?: string; // Cinematic 5-second video prompt generated by Gemini
  isGeneratingVideoPrompt?: boolean;
  createdAt: string;
}

const PRESET_IDEAS = [
  { label: 'Cipratan Air & Buah Segar', prompt: 'Inside a giant tropical jackfruit, cracked open to show product inside, beautiful crystal clear water splashes and floating fruit fibers, dramatic commercial photography lighting, 8k resolution.' },
  { label: 'Kristal & Batu Permata', prompt: 'Enclosed within massive glowing emerald gemstone crystals, sharp light fractures, floating reflective diamond dust, professional advertising background, premium look.' },
  { label: 'Lava Magma Membara', prompt: 'Sitting on dark cracked volcanic rocks filled with glowing orange lava streams, heat shimmer distortion, rising sparks and ash particles, intense high-contrast dramatic contrast.' },
  { label: 'Awan Kosmik & Nebula', prompt: 'Floating weightlessly in deep space, colorful glowing nebula clouds in magenta and royal blue, tiny floating asteroid particles, cinematic ambient lighting style, sci-fi premium advertising.' },
  { label: 'Buih Es Kristal Beku', prompt: 'Trapped inside a block of dynamic frozen crystal ice starting to shatter, sharp cracking lines, glowing studio illumination, extreme details of ice shards flying, cinematic close-up.' },
  { label: 'Aliran Neon Cyberpunk', prompt: 'On a wet asphalt street pavement at night, reflecting vibrant pink and cyan neon signboards, thin atmospheric fog, cybernetic city backdrop, bokeh commercial shot.' }
];

const RATIOS = [
  { label: '9:16', value: '9:16' },
  { label: '1:1', value: '1:1' },
  { label: '4:3', value: '4:3' },
  { label: '16:9', value: '16:9' }
];

const ENGINES = [
  { label: 'Fast Image', value: 'gemini-2.5-flash-image', desc: 'Sangat cepat & tajam' },
  { label: 'Ultra Image', value: 'gemini-3.1-flash-image', desc: 'Detail ultra 1K & realistis' }
];

const Scene: React.FC = () => {
  const { primaryColor } = useTheme();

  // Core States
  const [originalImage, setOriginalImage] = useState<string | null>(null);
  const [currentInputImage, setCurrentInputImage] = useState<string | null>(null);
  const [prompt, setPrompt] = useState<string>('');
  const [aspectRatio, setAspectRatio] = useState<string>('9:16');
  const [selectedEngine, setSelectedEngine] = useState<string>('gemini-2.5-flash-image');
  
  // Chain List State
  const [generatedScenes, setGeneratedScenes] = useState<GeneratedScene[]>([]);
  
  // Favorites State
  const [favorites, setFavorites] = useState<GeneratedScene[]>([]);
  
  // Navigation
  const [activeTab, setActiveTab] = useState<'generator' | 'favorit'>('generator');

  // UI / Copy Feedback
  const [copiedStates, setCopiedStates] = useState<{ [key: string]: boolean }>({});
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [generationProgress, setGenerationProgress] = useState<string>('');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  
  // Modal / Lightbox State
  const [previewImage, setPreviewImage] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Load cache on mount
  useEffect(() => {
    const cachedOrig = localStorage.getItem('guber_scene_origin_v2');
    const cachedInput = localStorage.getItem('guber_scene_current_v2');
    const cachedScenes = localStorage.getItem('guber_scene_list_v2');
    const cachedFavs = localStorage.getItem('guber_scene_favs_v2');
    const cachedRatio = localStorage.getItem('guber_scene_ratio_v2');
    const cachedPrompt = localStorage.getItem('guber_scene_prompt_v2');
    const cachedEngine = localStorage.getItem('guber_scene_engine_v2');

    if (cachedOrig) setOriginalImage(cachedOrig);
    if (cachedInput) setCurrentInputImage(cachedInput);
    if (cachedRatio) setAspectRatio(cachedRatio);
    if (cachedPrompt) setPrompt(cachedPrompt);
    if (cachedEngine) setSelectedEngine(cachedEngine);
    
    if (cachedScenes) {
      try {
        setGeneratedScenes(JSON.parse(cachedScenes));
      } catch (err) {
        console.error(err);
      }
    }
    if (cachedFavs) {
      try {
        setFavorites(JSON.parse(cachedFavs));
      } catch (err) {
        console.error(err);
      }
    }
  }, []);

  // Save changes helper
  const updateOriginalImage = (img: string | null) => {
    setOriginalImage(img);
    if (img) {
      localStorage.setItem('guber_scene_origin_v2', img);
      
      // If we don't have a current input image, or it's empty, set it
      if (!currentInputImage) {
        setCurrentInputImage(img);
        localStorage.setItem('guber_scene_current_v2', img);
      }
    } else {
      localStorage.removeItem('guber_scene_origin_v2');
      setCurrentInputImage(null);
      localStorage.removeItem('guber_scene_current_v2');
      setGeneratedScenes([]);
      localStorage.removeItem('guber_scene_list_v2');
    }
  };

  const updateCurrentInputImage = (img: string | null) => {
    setCurrentInputImage(img);
    if (img) {
      localStorage.setItem('guber_scene_current_v2', img);
    } else {
      localStorage.removeItem('guber_scene_current_v2');
    }
  };

  const saveScenesToCache = (list: GeneratedScene[]) => {
    setGeneratedScenes(list);
    localStorage.setItem('guber_scene_list_v2', JSON.stringify(list));
  };

  const saveFavoritesToCache = (list: GeneratedScene[]) => {
    setFavorites(list);
    localStorage.setItem('guber_scene_favs_v2', JSON.stringify(list));
  };

  // Upload handler
  const handleFileUpload = (file: File) => {
    if (!file.type.match('image.*')) {
      alert('Format file harus berupa gambar!');
      return;
    }
    const reader = new FileReader();
    reader.onload = (e) => {
      if (e.target?.result) {
        updateOriginalImage(e.target.result as string);
      }
    };
    reader.readAsDataURL(file);
  };

  const triggerInputClick = () => {
    fileInputRef.current?.click();
  };

  // Generate main action
  const handleGenerate = async () => {
    const referenceSrc = currentInputImage || originalImage;
    if (!referenceSrc) {
      setErrorMessage('Harap unggah gambar produk/sepatu referensi terlebih dahulu!');
      return;
    }
    if (!prompt.trim()) {
      setErrorMessage('Masukkan deskripsi scene singkat atau klik salah satu ide preset di bawah.');
      return;
    }

    setIsGenerating(true);
    setErrorMessage(null);
    setGenerationProgress('Menganalisis produk & membentuk adegan baru...');

    try {
      const generatedUrl = await generateScene(
        { prompt, aspectRatio },
        { reference: referenceSrc }
      );

      if (!generatedUrl) {
        throw new Error('AI tidak berhasil mengembalikan hasil gambar. Silakan coba lagi.');
      }

      const nextNumber = generatedScenes.length + 1;
      const newScene: GeneratedScene = {
        id: String(Date.now()),
        sceneNumber: nextNumber,
        inputImage: referenceSrc,
        generatedImage: generatedUrl,
        prompt: prompt,
        createdAt: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })
      };

      const updated = [...generatedScenes, newScene];
      saveScenesToCache(updated);
      setPrompt('');
      localStorage.removeItem('guber_scene_prompt_v2');
    } catch (err: any) {
      console.error(err);
      setErrorMessage(err.message || 'Terjadi gangguan jaringan atau kendala keamanan AI.');
    } finally {
      setIsGenerating(false);
      setGenerationProgress('');
    }
  };

  // Generate Video Prompt
  const handleMakeVideoPrompt = async (sceneId: string) => {
    const targetScene = generatedScenes.find(s => s.id === sceneId);
    if (!targetScene) return;

    // Set generating state localized to this card
    const updatedScenes = generatedScenes.map(sc => {
      if (sc.id === sceneId) {
        return { ...sc, isGeneratingVideoPrompt: true };
      }
      return sc;
    });
    setGeneratedScenes(updatedScenes);

    try {
      const videoResult = await generateSceneVideoPrompt(targetScene.generatedImage, targetScene.prompt);
      
      const finalized = generatedScenes.map(sc => {
        if (sc.id === sceneId) {
          return { ...sc, videoPrompt: videoResult, isGeneratingVideoPrompt: false };
        }
        return sc;
      });
      saveScenesToCache(finalized);
    } catch (err: any) {
      console.error(err);
      alert('Gagal menghasilkan prompt video: ' + (err.message || 'Error AI.'));
      const resetState = generatedScenes.map(sc => {
        if (sc.id === sceneId) {
          return { ...sc, isGeneratingVideoPrompt: false };
        }
        return sc;
      });
      setGeneratedScenes(resetState);
    }
  };

  // Use as next reference trigger
  const handleSetAsNextInput = (img: string) => {
    updateCurrentInputImage(img);
    // Smooth scroll back to input area
    window.scrollTo({ top: 0, behavior: 'smooth' });
    
    // Add brief alert indicator
    const feedback = document.getElementById('current-ref-indicator');
    if (feedback) {
      feedback.classList.add('animate-ping');
      setTimeout(() => feedback.classList.remove('animate-ping'), 1000);
    }
  };

  // Favourites toggler
  const handleToggleFavorite = (scene: GeneratedScene) => {
    const exists = favorites.some(fav => fav.id === scene.id);
    if (exists) {
      const filtered = favorites.filter(fav => fav.id !== scene.id);
      saveFavoritesToCache(filtered);
    } else {
      const appended = [...favorites, scene];
      saveFavoritesToCache(appended);
    }
  };

  const handleClearChain = () => {
    if (confirm('Yakin ingin mengatur ulang alur scene dan menghapus semua hasil generate di laci?')) {
      saveScenesToCache([]);
      updateCurrentInputImage(originalImage);
      setErrorMessage(null);
    }
  };

  const copyText = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedStates(prev => ({ ...prev, [key]: true }));
    setTimeout(() => {
      setCopiedStates(prev => ({ ...prev, [key]: false }));
    }, 2000);
  };

  const isSceneFavorited = (id: string) => favorites.some(fav => fav.id === id);

  return (
    <div className="h-screen bg-slate-50 flex flex-col overflow-hidden">
      {/* Top Professional App Bar Header */}
      <div className="h-16 bg-white border-b border-slate-200 flex items-center px-6 justify-between shrink-0 z-30 shadow-sm">
        <div className="flex items-center gap-3">
          <div 
            className="w-10 h-10 rounded-xl flex items-center justify-center text-white shadow-md"
            style={{ backgroundColor: primaryColor }}
          >
            <Sparkles size={20} className="animate-spin-slow" />
          </div>
          <div>
            <h1 className="text-sm font-black text-slate-800 tracking-tight uppercase leading-none">Affiliate Scene Chainer</h1>
            <p className="text-[9px] font-bold text-slate-400 uppercase tracking-[0.2em] mt-1">Skenario Berantai Video Kreatif</p>
          </div>
        </div>

        {/* Tab Controls */}
        <div className="flex bg-slate-100 p-1 rounded-xl border border-slate-200/50">
          <button
            onClick={() => setActiveTab('generator')}
            className={`px-4 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-wider transition-all flex items-center gap-1.5 ${
              activeTab === 'generator' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-400 hover:text-slate-600'
            }`}
          >
            <Zap size={12} style={activeTab === 'generator' ? { color: primaryColor } : {}} />
            Generator Scene
          </button>
          <button
            onClick={() => setActiveTab('favorit')}
            className={`px-4 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-wider transition-all flex items-center gap-1.5 relative ${
              activeTab === 'favorit' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-400 hover:text-slate-600'
            }`}
          >
            <Heart size={12} className={favorites.length > 0 ? 'fill-rose-500 text-rose-500' : ''} />
            Favorit ({favorites.length})
          </button>
        </div>
      </div>

      <div className="flex-1 flex flex-col lg:flex-row overflow-hidden relative">
        <AnimatePresence mode="wait">
          {activeTab === 'generator' ? (
            <motion.div
              key="generator-view"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="flex-1 flex flex-col lg:flex-row overflow-hidden w-full h-full"
            >
              {/* LEFT COLUMN: Input, Settings & Presets */}
              <div className="w-full lg:w-[380px] bg-white border-r border-slate-200 flex flex-col h-full shrink-0 z-10 overflow-y-auto custom-scrollbar">
                <div className="p-6 space-y-6">
                  
                  {/* Step 1: Upload Main Reference */}
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2 leading-none">
                      <span className="w-5 h-5 rounded-full bg-slate-100 flex items-center justify-center text-[10px] font-black" style={{ color: primaryColor }}>1</span>
                      UNGHAH PRODUK UTAMA
                    </label>
                    <p className="text-[11px] font-semibold text-slate-400 leading-normal">
                      Unggah produk asli (sepatu) sebagai titik awal / jangkar visual.
                    </p>

                    {!originalImage ? (
                      <div
                        onClick={triggerInputClick}
                        className="border-2 border-dashed border-slate-200 hover:border-slate-400 rounded-2xl p-6 bg-slate-50 flex flex-col items-center justify-center text-center cursor-pointer transition-all"
                        id="dropzone-area"
                      >
                        <ImageIcon size={32} className="text-slate-300 mb-2 animate-pulse" />
                        <span className="text-xs font-black text-slate-600">Klik / Seret foto produk</span>
                        <span className="text-[8.5px] font-black text-slate-400 uppercase tracking-wider mt-1">Format JPG, PNG, WEBP</span>
                        <input
                          type="file"
                          ref={fileInputRef}
                          onChange={(e) => {
                            if (e.target.files?.[0]) handleFileUpload(e.target.files[0]);
                          }}
                          className="hidden"
                          accept="image/*"
                        />
                      </div>
                    ) : (
                      <div className="relative rounded-2xl border-2 border-slate-100 overflow-hidden bg-slate-900 group">
                        <img 
                          src={originalImage} 
                          alt="Model reference" 
                          className="w-full h-36 object-contain bg-slate-950/20"
                        />
                        <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-all flex items-center justify-center gap-2">
                          <button
                            onClick={triggerInputClick}
                            className="bg-white hover:bg-slate-50 text-slate-800 px-3 py-1.5 rounded-xl font-bold text-[10px] tracking-wide"
                          >
                            Ganti
                          </button>
                          <button
                            onClick={() => updateOriginalImage(null)}
                            className="bg-rose-600 hover:bg-rose-700 text-white px-3 py-1.5 rounded-xl font-bold text-[10px] tracking-wide"
                          >
                            Hapus
                          </button>
                        </div>
                        <input
                          type="file"
                          ref={fileInputRef}
                          onChange={(e) => {
                            if (e.target.files?.[0]) handleFileUpload(e.target.files[0]);
                          }}
                          className="hidden"
                          accept="image/*"
                        />
                      </div>
                    )}
                  </div>

                  {/* Step 2: Prompt Input */}
                  <div className="space-y-2 pt-4 border-t border-slate-100">
                    <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2 leading-none">
                      <span className="w-5 h-5 rounded-full bg-slate-100 flex items-center justify-center text-[10px] font-black" style={{ color: primaryColor }}>2</span>
                      DESKRIPSI SCENE BERIKUTNYA
                    </label>
                    <textarea
                      value={prompt}
                      onChange={(e) => {
                        setPrompt(e.target.value);
                        localStorage.setItem('guber_scene_prompt_v2', e.target.value);
                      }}
                      placeholder="Masukkan konsep scene kreatif (misal: di puncak gunung lava membara, dibelah buah durian segar)..."
                      className="w-full text-xs font-bold p-4 bg-slate-50 border-2 border-slate-100 rounded-2xl focus:border-slate-200 focus:outline-none transition-all resize-none shadow-inner h-24 placeholder:text-slate-300"
                    />
                  </div>

                  {/* Preset Suggestions */}
                  <div className="space-y-1.5">
                    <span className="text-[8px] font-black text-slate-400 uppercase tracking-widest block">Rekomendasi Presisi Scene</span>
                    <div className="grid grid-cols-1 gap-1 max-h-40 overflow-y-auto pr-1 custom-scrollbar">
                      {PRESET_IDEAS.map((idea, idx) => (
                        <button
                          key={idx}
                          onClick={() => {
                            setPrompt(idea.prompt);
                            localStorage.setItem('guber_scene_prompt_v2', idea.prompt);
                          }}
                          className="w-full text-left p-2 rounded-xl bg-slate-50 hover:bg-slate-100 border border-slate-100/50 text-slate-700 text-[10px] font-extrabold line-clamp-1 transition-colors"
                        >
                          ✨ {idea.label}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Step 3: Aspect Ratio */}
                  <div className="space-y-2 pt-4 border-t border-slate-100">
                    <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2 leading-none">
                      <span className="w-5 h-5 rounded-full bg-slate-100 flex items-center justify-center text-[10px] font-black" style={{ color: primaryColor }}>3</span>
                      ASPEK RASIO
                    </label>
                    <div className="grid grid-cols-4 gap-1.5">
                      {RATIOS.map((r) => (
                        <button
                          key={r.value}
                          onClick={() => {
                            setAspectRatio(r.value);
                            localStorage.setItem('guber_scene_ratio_v2', r.value);
                          }}
                          className={`p-2 rounded-xl border text-center transition-all ${
                            aspectRatio === r.value 
                              ? 'bg-slate-900 border-slate-900 text-white font-black scale-105 shadow-sm' 
                              : 'bg-slate-50 border-slate-100 text-slate-400 font-bold hover:bg-slate-100 hover:text-slate-600'
                          }`}
                        >
                          <span className="text-[9px] tracking-tighter uppercase">{r.label}</span>
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Engine Configuration */}
                  <div className="space-y-2 pt-4 border-t border-slate-100">
                    <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block leading-none">REKAYASA MESIN IMAGE AI</label>
                    <div className="grid grid-cols-2 gap-2">
                      {ENGINES.map((eng) => (
                        <button
                          key={eng.value}
                          onClick={() => {
                            setSelectedEngine(eng.value);
                            localStorage.setItem('guber_scene_engine_v2', eng.value);
                          }}
                          className={`p-2.5 rounded-xl border text-left transition-all flex flex-col justify-between ${
                            selectedEngine === eng.value 
                              ? 'bg-white border-slate-900 text-slate-900 shadow-md scale-102' 
                              : 'bg-slate-50/50 border-slate-100 text-slate-400 hover:bg-slate-50'
                          }`}
                          style={selectedEngine === eng.value ? { borderColor: primaryColor } : {}}
                        >
                          <span className="text-[10px] font-black" style={selectedEngine === eng.value ? { color: primaryColor } : {}}>{eng.label}</span>
                          <span className="text-[8px] text-slate-400 font-medium leading-none block mt-0.5">{eng.desc}</span>
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* CTA Generate Buttons */}
                  <div className="pt-4 border-t border-slate-100">
                    <button
                      onClick={handleGenerate}
                      disabled={isGenerating || (!originalImage)}
                      className="w-full text-white font-black uppercase text-xs tracking-widest py-4 rounded-2xl shadow-lg transition-transform active:scale-[0.98] flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                      style={{ backgroundColor: primaryColor }}
                      id="generate-cta-btn"
                    >
                      {isGenerating ? (
                        <>
                          <RefreshCw size={14} className="animate-spin" />
                          <span>MENCIPTAKAN SCENE...</span>
                        </>
                      ) : (
                        <>
                          <Sparkles size={14} />
                          <span>HASILKAN SCENE BARU</span>
                        </>
                      )}
                    </button>
                  </div>

                </div>
              </div>

              {/* RIGHT COLUMN: Active Chaining State and Generated Stories */}
              <div className="flex-1 bg-slate-50/60 overflow-y-auto p-6 md:p-8 custom-scrollbar">
                
                {/* Current reference banner */}
                {originalImage && (
                  <div className="mb-6 bg-white border border-slate-200/85 rounded-3xl p-4 flex flex-col sm:flex-row items-center justify-between gap-4 max-w-4xl mx-auto shadow-sm">
                    <div className="flex items-center gap-3 w-full sm:w-auto">
                      <div className="relative w-12 h-16 bg-slate-900 rounded-xl overflow-hidden shadow-inner border border-slate-200 shrink-0">
                        <img 
                          src={currentInputImage || originalImage} 
                          alt="Active input reference" 
                          className="w-full h-full object-contain"
                        />
                        <span id="current-ref-indicator" className="absolute top-1 right-1 w-2.5 h-2.5 bg-emerald-500 rounded-full border border-white" />
                      </div>
                      <div className="text-left">
                        <span className="bg-emerald-50 text-emerald-700 text-[8.5px] font-black uppercase px-2 py-0.5 rounded-md tracking-wider">
                          Referensi Aktif
                        </span>
                        <h4 className="text-[11px] font-black text-slate-800 uppercase mt-1 leading-tight">
                          {currentInputImage === originalImage ? 'Produk Utama / Titik Awal' : `Hasil generate Scene #${generatedScenes.find(s => s.generatedImage === currentInputImage)?.sceneNumber || ''}`}
                        </h4>
                        <p className="text-[9px] text-slate-400 font-semibold leading-none mt-1">
                          Scene berikutnya akan ditumpangkan dari gambar referensi ini.
                        </p>
                      </div>
                    </div>

                    <div className="flex gap-2 w-full sm:w-auto shrink-0 justify-end">
                      {currentInputImage !== originalImage && (
                        <button
                          onClick={() => updateCurrentInputImage(originalImage)}
                          className="bg-slate-100 hover:bg-slate-200 text-slate-600 px-3 py-1.5 rounded-xl font-bold text-[9.5px] uppercase tracking-wider transition-colors"
                        >
                          Ganti ke Produk Awal
                        </button>
                      )}
                      {generatedScenes.length > 0 && (
                        <button
                          onClick={handleClearChain}
                          className="bg-rose-50 hover:bg-rose-100 text-rose-600 px-3 py-1.5 rounded-xl font-bold text-[9.5px] uppercase tracking-wider transition-colors flex items-center gap-1"
                        >
                          <Trash2 size={10} />
                          Bersihkan Alur
                        </button>
                      )}
                    </div>
                  </div>
                )}

                {/* Main feedback messages */}
                {errorMessage && (
                  <div className="mb-6 max-w-4xl mx-auto bg-rose-50 border border-rose-200/50 p-4 rounded-2xl flex items-start gap-3">
                    <AlertCircle size={16} className="text-rose-600 shrink-0 mt-0.5" />
                    <div>
                      <h4 className="text-xs font-black text-rose-800 uppercase leading-none">Terjadi Hambatan</h4>
                      <p className="text-[11px] text-rose-600 font-bold mt-1 leading-relaxed">{errorMessage}</p>
                    </div>
                  </div>
                )}

                {/* Empty State vs Storyboard List */}
                {generatedScenes.length === 0 ? (
                  <div className="h-[70%] flex flex-col items-center justify-center text-center p-8 max-w-md mx-auto">
                    <div className="w-16 h-16 bg-white border border-slate-200 rounded-[24px] flex items-center justify-center text-slate-400 mb-4 shadow-sm">
                      <ImageIcon size={30} className="animate-pulse" />
                    </div>
                    <h3 className="text-xs font-black text-slate-700 uppercase tracking-widest">Alur Storyboard Skenario Kosong</h3>
                    <p className="text-[10.5px] text-slate-400 font-bold leading-relaxed mt-2 uppercase tracking-wide">
                      Ikuti Alur Kreatif 1-2-3:
                    </p>
                    <ul className="text-left text-[11px] text-slate-500 font-medium space-y-2 mt-3 list-decimal list-inside pl-1 bg-white p-4 rounded-2xl border border-slate-200/50">
                      <li>Unggah foto produk asli Anda sebagai referensi dasar.</li>
                      <li>Masukkan deskripsi scenario (Contoh: "dibelah di dalam semangka matang").</li>
                      <li>Tekan tombol generate untuk melihat <span className="font-extrabold text-slate-800">Hasil Generate 1</span>.</li>
                      <li>Ketik <span className="font-extrabold text-slate-800">+</span> pada hasil untuk menjadikannya rujukan scene lanjutan!</li>
                    </ul>
                  </div>
                ) : (
                  <div className="space-y-8 max-w-4xl mx-auto pb-20">
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                        DAFTAR HASIL SKENARIO BERANTAI
                      </span>
                      <span className="bg-slate-200 text-slate-700 text-[9px] font-black px-2.5 py-1 rounded-full uppercase">
                        {generatedScenes.length} total scene
                      </span>
                    </div>

                    <div className="space-y-6">
                      {generatedScenes.map((scene, index) => (
                        <div 
                          key={scene.id}
                          className="bg-white border border-slate-200/80 rounded-[32px] overflow-hidden shadow-sm hover:shadow-md transition-shadow relative flex flex-col md:flex-row group"
                        >
                          {/* Left: Input reference info thumbnail & comparison */}
                          <div className="w-full md:w-[150px] bg-slate-50 border-r border-slate-100 p-4 shrink-0 flex flex-col justify-between gap-4">
                            <div>
                              <span className="text-[8px] font-black text-slate-400 uppercase tracking-widest block mb-1">DARI DRAWING REF</span>
                              <div className="w-full aspect-[3/4] rounded-xl bg-slate-900 border border-slate-200 shadow-inner overflow-hidden relative">
                                <img 
                                  src={scene.inputImage} 
                                  alt="Reference source" 
                                  className="w-full h-full object-contain"
                                />
                              </div>
                            </div>

                            <div className="text-left bg-white/85 p-2 rounded-xl border border-slate-200/40">
                              <span className="text-[8px] font-black text-slate-400 block leading-none">Prompt Singkat:</span>
                              <p className="text-[10px] text-slate-600 font-black mt-1 leading-tight line-clamp-3">
                                "{scene.prompt}"
                              </p>
                            </div>
                          </div>

                          {/* Center / Image Stage Result */}
                          <div className="flex-1 p-6 flex flex-col sm:flex-row gap-6">
                            
                            {/* Generated Image Thumbnail */}
                            <div className="w-full sm:w-[200px] shrink-0">
                              <div className="aspect-[9/16] rounded-2xl border-4 border-slate-50 bg-slate-900 relative shadow-inner overflow-hidden group/image">
                                <img 
                                  src={scene.generatedImage} 
                                  alt={`Scene Result ${scene.sceneNumber}`} 
                                  className="w-full h-full object-cover"
                                  referrerPolicy="no-referrer"
                                />
                                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover/image:opacity-100 transition-opacity flex flex-col items-center justify-center gap-1.5 p-3">
                                  <button
                                    onClick={() => setPreviewImage(scene.generatedImage)}
                                    className="bg-white text-slate-800 p-2 rounded-xl text-[10px] font-black uppercase tracking-wider shadow-md hover:scale-105 active:scale-95 transition-transform"
                                  >
                                    Perbesar
                                  </button>
                                  <a
                                    href={scene.generatedImage}
                                    download={`story-scene-${scene.sceneNumber}.png`}
                                    className="bg-emerald-600 text-white p-2 rounded-xl text-[10px] font-black uppercase tracking-wider shadow-md hover:scale-105 active:scale-95 transition-transform flex items-center gap-1"
                                  >
                                    <Download size={10} /> Unduh
                                  </a>
                                </div>
                              </div>
                            </div>

                            {/* Info Actions Workspace */}
                            <div className="flex-1 flex flex-col justify-between gap-4">
                              <div>
                                <div className="flex items-center justify-between">
                                  <div className="flex items-center gap-2">
                                    <span className="w-6 h-6 rounded-lg bg-slate-900 text-white font-black text-[10px] flex items-center justify-center">
                                      {scene.sceneNumber}
                                    </span>
                                    <h3 className="font-extrabold text-slate-800 text-xs uppercase tracking-wider">
                                      Hasil Generate #{scene.sceneNumber}
                                    </h3>
                                  </div>

                                  <div className="flex items-center gap-1.5">
                                    {/* Favorite button icon */}
                                    <button
                                      onClick={() => handleToggleFavorite(scene)}
                                      className="p-1.5 rounded-lg border border-slate-100 text-slate-400 hover:text-rose-600 hover:bg-slate-50 transition-colors"
                                      title="Simpan ke Favorit"
                                    >
                                      <Heart size={14} className={isSceneFavorited(scene.id) ? 'fill-rose-500 text-rose-500' : ''} />
                                    </button>
                                  </div>
                                </div>

                                <div className="mt-4 p-4 bg-slate-50 rounded-2xl border border-slate-100 flex flex-col gap-3">
                                  {/* Next-reference chain linker (+) icon */}
                                  <button
                                    onClick={() => handleSetAsNextInput(scene.generatedImage)}
                                    className="w-full bg-emerald-50 hover:bg-emerald-100 border border-emerald-200 text-emerald-700 py-2 px-4 rounded-xl font-black text-[10px] uppercase tracking-wider flex items-center justify-center gap-2 transition-all active:scale-[0.98]"
                                  >
                                    <Plus size={14} />
                                    <span>Gunakan untuk Scene Selanjutnya (+)</span>
                                  </button>

                                  {/* Prompt video generator block */}
                                  <div className="border-t border-slate-200/60 pt-3">
                                    {!scene.videoPrompt ? (
                                      <button
                                        onClick={() => handleMakeVideoPrompt(scene.id)}
                                        disabled={scene.isGeneratingVideoPrompt}
                                        className="w-full bg-slate-900 hover:bg-slate-800 disabled:opacity-50 text-white py-2 px-3 rounded-xl font-black text-[10px] uppercase tracking-widest flex items-center justify-center gap-1.5 transition-colors"
                                      >
                                        {scene.isGeneratingVideoPrompt ? (
                                          <>
                                            <RefreshCw size={12} className="animate-spin" />
                                            <span>MENGURAIKAN VIDEO PROMPT...</span>
                                          </>
                                        ) : (
                                          <>
                                            <Film size={12} />
                                            <span>Hasilkan Video Prompt (5s)</span>
                                          </>
                                        )}
                                      </button>
                                    ) : (
                                      <div className="space-y-1.5 text-left">
                                        <div className="flex justify-between items-center">
                                          <span className="text-[8px] font-black text-indigo-600 uppercase tracking-widest block">PROMPT VIDEO 5-DETIK</span>
                                          <button
                                            onClick={() => copyText(scene.videoPrompt || '', `vid-${scene.id}`)}
                                            className="text-[9px] font-bold text-slate-400 hover:text-slate-600 flex items-center gap-1"
                                          >
                                            {copiedStates[`vid-${scene.id}`] ? (
                                              <>
                                                <Check size={10} className="text-emerald-500" />
                                                <span className="text-emerald-600">Terkompresi!</span>
                                              </>
                                            ) : (
                                              <>
                                                <Copy size={10} />
                                                <span>Salin</span>
                                              </>
                                            )}
                                          </button>
                                        </div>
                                        <p className="text-[10.5px] font-mono leading-relaxed bg-indigo-50/50 p-2.5 rounded-xl border border-indigo-100 text-slate-700 font-bold select-all">
                                          {scene.videoPrompt}
                                        </p>
                                      </div>
                                    )}
                                  </div>

                                </div>
                              </div>

                              <div className="text-right">
                                <span className="text-[8px] font-medium text-slate-300">Waktu proses: {scene.createdAt}</span>
                              </div>
                            </div>

                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

              </div>
            </motion.div>
          ) : (
            /* Tab Favorit: Display Saved Individual Scenes */
            <motion.div
              key="favorites-view"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="flex-1 overflow-y-auto p-6 md:p-12 w-full h-full custom-scrollbar bg-slate-50"
            >
              <div className="max-w-5xl mx-auto space-y-6">
                <div>
                  <h2 className="text-sm font-black text-slate-800 uppercase tracking-widest flex items-center gap-2">
                    <Heart size={16} className="fill-rose-500 text-rose-500 animate-bounce" />
                    Katalog Adegan Favorit
                  </h2>
                  <p className="text-[9px] font-bold text-slate-400 uppercase tracking-[0.2em] mt-1">
                    Kumpulan scene paling wow yang telah Anda favoritkan
                  </p>
                </div>

                {favorites.length === 0 ? (
                  <div className="bg-white border border-slate-200 rounded-[32px] p-16 text-center shadow-sm flex flex-col items-center justify-center max-w-md mx-auto mt-12">
                    <Heart size={36} className="text-slate-200 mb-4" />
                    <h3 className="text-xs font-black text-slate-700 uppercase tracking-wider">Katalog Masih Kosong</h3>
                    <p className="text-[11px] text-slate-400 mt-1 max-w-xs font-semibold leading-relaxed">
                      Selesai menghasilkan gambar scene di generator, ketuk ikon hati di kartu adegan untuk menyimpannya ke daftar favorit ini.
                    </p>
                    <button
                      onClick={() => setActiveTab('generator')}
                      className="mt-6 text-white font-black uppercase text-[10px] tracking-wider px-5 py-3 rounded-2xl shadow-md transition-all active:scale-95"
                      style={{ backgroundColor: primaryColor }}
                    >
                      Mulai Eksplorasi Generator
                    </button>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6" id="favorites-grid">
                    {favorites.map((fav) => (
                      <div
                        key={fav.id}
                        className="bg-white border border-slate-200 rounded-3xl p-5 shadow-sm hover:shadow-md transition-all flex gap-4 pr-10 relative"
                      >
                        {/* Image stage */}
                        <div className="w-[100px] aspect-[9/16] rounded-2xl bg-slate-900 overflow-hidden relative shadow-md shrink-0">
                          <img 
                            src={fav.generatedImage} 
                            alt="Favorite Scene" 
                            className="w-full h-full object-cover"
                          />
                        </div>

                        {/* Text and Actions */}
                        <div className="flex-1 flex flex-col justify-between py-1 text-left">
                          <div>
                            <span className="bg-slate-900 text-white text-[8px] font-black uppercase px-2 py-0.5 rounded">
                              SCENE #{fav.sceneNumber}
                            </span>
                            <p className="text-[11px] text-slate-700 font-extrabold leading-relaxed mt-2.5 line-clamp-2">
                              "{fav.prompt}"
                            </p>
                            
                            {fav.videoPrompt && (
                              <div className="mt-2.5 p-2 bg-indigo-50/50 rounded-xl border border-indigo-100">
                                <span className="text-[8px] font-black text-indigo-600 block mb-0.5">VIDEO PROMPT:</span>
                                <p className="text-[9.5px] font-mono leading-tight text-slate-600 line-clamp-3 select-all">
                                  {fav.videoPrompt}
                                </p>
                              </div>
                            )}
                          </div>

                          <div className="flex items-center justify-between border-t border-slate-100 pt-3 mt-4">
                            <button
                              onClick={() => {
                                updateCurrentInputImage(fav.generatedImage);
                                setActiveTab('generator');
                                window.scrollTo({ top: 0, behavior: 'smooth' });
                              }}
                              className="text-[9px] font-black uppercase tracking-wider text-emerald-600 hover:text-emerald-700 flex items-center gap-1"
                            >
                              Gunakan Rujukan <Plus size={10} />
                            </button>

                            <a
                              href={fav.generatedImage}
                              download={`fav-scene-${fav.id}.png`}
                              className="text-[9px] font-black uppercase tracking-wider text-slate-500 hover:text-slate-700"
                            >
                              Unduh Gambar
                            </a>
                          </div>
                        </div>

                        {/* Top corner fav toggler */}
                        <button
                          onClick={() => handleToggleFavorite(fav)}
                          className="absolute top-4 right-4 text-rose-500 hover:text-slate-300 p-1 rounded-lg transition-colors"
                          title="Hapus dari Favorit"
                        >
                          <Trash2 size={15} />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Enlarged Image Lightbox */}
      <AnimatePresence>
        {previewImage && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] bg-black/95 backdrop-blur-xl flex items-center justify-center p-4 lg:p-12"
          >
            <button
              onClick={() => setPreviewImage(null)}
              className="absolute top-6 right-6 text-white/50 hover:text-white transition-colors p-2"
              title="Tutup"
            >
              <X size={40} />
            </button>
            <img
              src={previewImage}
              className="max-w-full max-h-[85vh] object-contain rounded-2xl shadow-2xl border border-white/10"
              alt="Enlarged visualization"
              referrerPolicy="no-referrer"
            />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default Scene;
